---
- hosts: all
  sudo: true
  roles:
    - role: .
      dnsmasq_conf_domain: "local"
      dnsmasq_conf_dhcp:
        eth0:
          range: ["10.0.1.100", "10.0.1.200", "infinite"]
          ignore_names: true
          generate_names: true
          option:
            - "option:router,{{ ansible_default_ipv4.gateway }}"
            - "option:dns-server,{{ ansible_eth0.ipv4.address }}"
          boot: [ "pxelinux.0" ]
          tftp: "/tmp"


#   - name: Display all variables/facts known for a host
#     debug: var=hostvars[inventory_hostname]

